spring:  
  application:
    name: admin-service
  cloud:
    consul:
      host: localhost
      port: 8500
  output.ansi.enabled: ALWAYS

  data:
    mongodb:
      database: AdminDashboard
      port: 27017
      host: localhost

feign:
  circuitbreaker:
    enabled: true
